// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtbgapjjcgmdzyttwcqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0YmdhcGpqY2dtZHp5dHR3Y3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODc1MzUsImV4cCI6MjA2NDQ2MzUzNX0.npwNc_dHbjWxYdUXZbXwyGWeFwrVynqjJ4hhhs6O2rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);